#ifndef PROPOSITIONALORINTRODUCTIONPLUGIN_GLOBAL_H
#define PROPOSITIONALORINTRODUCTIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPOSITIONALORINTRODUCTIONPLUGIN_LIBRARY)
#  define PROPOSITIONALORINTRODUCTIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPOSITIONALORINTRODUCTIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPOSITIONALORINTRODUCTIONPLUGIN_GLOBAL_H
