#ifndef AUTOMATICPROPOSITIONALLOGICSIGNATURE_GLOBAL_H
#define AUTOMATICPROPOSITIONALLOGICSIGNATURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUTOMATICPROPOSITIONALLOGICSIGNATURE_LIBRARY)
#  define AUTOMATICPROPOSITIONALLOGICSIGNATURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUTOMATICPROPOSITIONALLOGICSIGNATURESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOMATICPROPOSITIONALLOGICSIGNATURE_GLOBAL_H
