#ifndef PROPOSITIONALANDELIMINATIONPLUGIN_GLOBAL_H
#define PROPOSITIONALANDELIMINATIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPOSITIONALANDELIMINATIONPLUGIN_LIBRARY)
#  define PROPOSITIONALANDELIMINATIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPOSITIONALANDELIMINATIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPOSITIONALANDELIMINATIONPLUGIN_GLOBAL_H
