#ifndef PROPOSITIONALORELIMINATIONPLUGIN_GLOBAL_H
#define PROPOSITIONALORELIMINATIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPOSITIONALORELIMINATIONPLUGIN_LIBRARY)
#  define PROPOSITIONALORELIMINATIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPOSITIONALORELIMINATIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPOSITIONALORELIMINATIONPLUGIN_GLOBAL_H
