#ifndef PROPOSITIONALANDINTRODUCTIONPLUGIN_GLOBAL_H
#define PROPOSITIONALANDINTRODUCTIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPOSITIONALANDINTRODUCTIONPLUGIN_LIBRARY)
#  define PROPOSITIONALANDINTRODUCTIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPOSITIONALANDINTRODUCTIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPOSITIONALANDINTRODUCTIONPLUGIN_GLOBAL_H
