#ifndef PROOFWITHHYPOTHESISPLUGIN_GLOBAL_H
#define PROOFWITHHYPOTHESISPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROOFWITHHYPOTHESISPLUGIN_LIBRARY)
#  define PROOFWITHHYPOTHESISPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROOFWITHHYPOTHESISPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROOFWITHHYPOTHESISPLUGIN_GLOBAL_H
